s="Lucknow junction"
print(s.capitalize())
print(s.casefold())
print(s.center(30, "-"))
print(s.count("o"))
print(s.encode())
print(s.endswith("junction"))
s1 = "Lucknow\tjunction"
print(s1.expandtabs(4))
print(s.find("junction"))
name = "Lucknow"
print("City is {}".format(name))
data = {"city": "Lucknow"}
print("City is {city}".format_map(data))
print(s.index("junction"))
print(s.isalnum())
print(s.isalpha())
print(s.isascii())
print(s.isdecimal())
print(s.isdigit())
print(s.isidentifier())
print(s.islower())
print(s.isnumeric())
print(s.isprintable())
print(s.isspace())
print(s.istitle())
print(s.isupper())
words = ["Lucknow", "junction"]
print(" ".join(words))
print(s.ljust(30, "-"))
print(s.lower())
s2 = "   Lucknow junction"
print(s2.lstrip())
table = str.maketrans("L", "l")
print(s.translate(table))
print(s.partition(" "))
print(s.removeprefix("Lucknow "))
print(s.removesuffix(" junction"))
print(s.replace("junction", "Junction"))
print(s.rfind("n"))
print(s.rindex("n"))
print(s.rjust(30, "-"))
print(s.rpartition(" "))
print(s.rsplit(" ", 1))
s3 = "Lucknow junction   "
print(s3.rstrip())
print(s.split(" "))
s4 = "Lucknow\njunction"
print(s4.splitlines())
print(s.startswith("Lucknow"))
s5 = "   Lucknow junction   "
print(s5.strip())
print(s.swapcase())
print(s.title())
table = str.maketrans("L", "M")
print(s.translate(table))
print(s.upper())
print(s.zfill(30))
